# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /root/Graph/CliqueProblemeGraph

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /root/Graph/CliqueProblemeGraph

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /root/Graph/CliqueProblemeGraph/CMakeFiles /root/Graph/CliqueProblemeGraph//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /root/Graph/CliqueProblemeGraph/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named exemple

# Build rule for target.
exemple: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 exemple
.PHONY : exemple

# fast build rule for target.
exemple/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exemple.dir/build.make CMakeFiles/exemple.dir/build
.PHONY : exemple/fast

clique_solver.o: clique_solver.cpp.o
.PHONY : clique_solver.o

# target to build an object file
clique_solver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exemple.dir/build.make CMakeFiles/exemple.dir/clique_solver.cpp.o
.PHONY : clique_solver.cpp.o

clique_solver.i: clique_solver.cpp.i
.PHONY : clique_solver.i

# target to preprocess a source file
clique_solver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exemple.dir/build.make CMakeFiles/exemple.dir/clique_solver.cpp.i
.PHONY : clique_solver.cpp.i

clique_solver.s: clique_solver.cpp.s
.PHONY : clique_solver.s

# target to generate assembly for a file
clique_solver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exemple.dir/build.make CMakeFiles/exemple.dir/clique_solver.cpp.s
.PHONY : clique_solver.cpp.s

graph.o: graph.cpp.o
.PHONY : graph.o

# target to build an object file
graph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exemple.dir/build.make CMakeFiles/exemple.dir/graph.cpp.o
.PHONY : graph.cpp.o

graph.i: graph.cpp.i
.PHONY : graph.i

# target to preprocess a source file
graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exemple.dir/build.make CMakeFiles/exemple.dir/graph.cpp.i
.PHONY : graph.cpp.i

graph.s: graph.cpp.s
.PHONY : graph.s

# target to generate assembly for a file
graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exemple.dir/build.make CMakeFiles/exemple.dir/graph.cpp.s
.PHONY : graph.cpp.s

graphs/adjmat.o: graphs/adjmat.cpp.o
.PHONY : graphs/adjmat.o

# target to build an object file
graphs/adjmat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exemple.dir/build.make CMakeFiles/exemple.dir/graphs/adjmat.cpp.o
.PHONY : graphs/adjmat.cpp.o

graphs/adjmat.i: graphs/adjmat.cpp.i
.PHONY : graphs/adjmat.i

# target to preprocess a source file
graphs/adjmat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exemple.dir/build.make CMakeFiles/exemple.dir/graphs/adjmat.cpp.i
.PHONY : graphs/adjmat.cpp.i

graphs/adjmat.s: graphs/adjmat.cpp.s
.PHONY : graphs/adjmat.s

# target to generate assembly for a file
graphs/adjmat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exemple.dir/build.make CMakeFiles/exemple.dir/graphs/adjmat.cpp.s
.PHONY : graphs/adjmat.cpp.s

graphs/graphHeavy.o: graphs/graphHeavy.cpp.o
.PHONY : graphs/graphHeavy.o

# target to build an object file
graphs/graphHeavy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exemple.dir/build.make CMakeFiles/exemple.dir/graphs/graphHeavy.cpp.o
.PHONY : graphs/graphHeavy.cpp.o

graphs/graphHeavy.i: graphs/graphHeavy.cpp.i
.PHONY : graphs/graphHeavy.i

# target to preprocess a source file
graphs/graphHeavy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exemple.dir/build.make CMakeFiles/exemple.dir/graphs/graphHeavy.cpp.i
.PHONY : graphs/graphHeavy.cpp.i

graphs/graphHeavy.s: graphs/graphHeavy.cpp.s
.PHONY : graphs/graphHeavy.s

# target to generate assembly for a file
graphs/graphHeavy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exemple.dir/build.make CMakeFiles/exemple.dir/graphs/graphHeavy.cpp.s
.PHONY : graphs/graphHeavy.cpp.s

graphs/graphListAdj.o: graphs/graphListAdj.cpp.o
.PHONY : graphs/graphListAdj.o

# target to build an object file
graphs/graphListAdj.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exemple.dir/build.make CMakeFiles/exemple.dir/graphs/graphListAdj.cpp.o
.PHONY : graphs/graphListAdj.cpp.o

graphs/graphListAdj.i: graphs/graphListAdj.cpp.i
.PHONY : graphs/graphListAdj.i

# target to preprocess a source file
graphs/graphListAdj.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exemple.dir/build.make CMakeFiles/exemple.dir/graphs/graphListAdj.cpp.i
.PHONY : graphs/graphListAdj.cpp.i

graphs/graphListAdj.s: graphs/graphListAdj.cpp.s
.PHONY : graphs/graphListAdj.s

# target to generate assembly for a file
graphs/graphListAdj.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exemple.dir/build.make CMakeFiles/exemple.dir/graphs/graphListAdj.cpp.s
.PHONY : graphs/graphListAdj.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exemple.dir/build.make CMakeFiles/exemple.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exemple.dir/build.make CMakeFiles/exemple.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exemple.dir/build.make CMakeFiles/exemple.dir/main.cpp.s
.PHONY : main.cpp.s

utils.o: utils.cpp.o
.PHONY : utils.o

# target to build an object file
utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exemple.dir/build.make CMakeFiles/exemple.dir/utils.cpp.o
.PHONY : utils.cpp.o

utils.i: utils.cpp.i
.PHONY : utils.i

# target to preprocess a source file
utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exemple.dir/build.make CMakeFiles/exemple.dir/utils.cpp.i
.PHONY : utils.cpp.i

utils.s: utils.cpp.s
.PHONY : utils.s

# target to generate assembly for a file
utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/exemple.dir/build.make CMakeFiles/exemple.dir/utils.cpp.s
.PHONY : utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... exemple"
	@echo "... clique_solver.o"
	@echo "... clique_solver.i"
	@echo "... clique_solver.s"
	@echo "... graph.o"
	@echo "... graph.i"
	@echo "... graph.s"
	@echo "... graphs/adjmat.o"
	@echo "... graphs/adjmat.i"
	@echo "... graphs/adjmat.s"
	@echo "... graphs/graphHeavy.o"
	@echo "... graphs/graphHeavy.i"
	@echo "... graphs/graphHeavy.s"
	@echo "... graphs/graphListAdj.o"
	@echo "... graphs/graphListAdj.i"
	@echo "... graphs/graphListAdj.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... utils.o"
	@echo "... utils.i"
	@echo "... utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

